(* ::Package:: *)

(* ::Input:: *)
(*LGMag::usage = "LGMag[l, p]";*)
(*LGPhase::usage = "LGPhase[l, p]";*)
(*TwoLGMag::uage = "TwoLGMag[l0, p0, l1, p1]";*)
(*TwoLGPhase::usage = "TwoLGPhase[l0, p0, l1, p1]";*)
(*StartLG::usage = "StartLG[file] link";*)
(**)


(* ::Input:: *)
(*path = None;*)
(*link = None;*)
(*DEFAULTS={*)
(*Width-> 500,*)
(*Height-> 500,*)
(*WaveVector-> 1.0,*)
(*BeamWaist-> 10.0,*)
(*ScalingFactor-> {1,1},*)
(*Z-> 0.01,*)
(*Clamp-> True*)
(*};*)
(**)
(*StartLG[file_]:= Module[{},*)
(*If[link!=None,Uninstall[link]; link = None;];*)
(*link = Install[file];*)
(*path=file;*)
(*];*)
(**)
(*LGMag[l_, p_, OptionsPattern[Join[{Raw-> False},DEFAULTS]]]:= Module[{xscale, yscale,w0,w,h,cl,z,bytes,k,li,pi},*)
(*{xscale, yscale} = {N[OptionValue[ScalingFactor][[1]]], N[OptionValue[ScalingFactor][[2]]]};*)
(*w=IntegerPart[OptionValue[Width]];*)
(*h=IntegerPart[OptionValue[Height]];*)
(*cl=If[OptionValue[Clamp],1, 0];*)
(*li =IntegerPart[l];*)
(*pi=IntegerPart[p];*)
(**)
(*k=N[OptionValue[WaveVector]];*)
(*w0=N[OptionValue[BeamWaist]];*)
(*z=Re[OptionValue[Z]];*)
(**)
(*bytes=Check[LaguerreGuassianMag[*)
(*w, h, xscale, yscale, li, pi, k,w0,z,cl*)
(*],Abort[]];*)
(**)
(*If[OptionValue[Raw], bytes, Image[bytes]]*)
(*];*)
(**)
(*LGPhase[l_, p_, OptionsPattern[Join[{Raw-> False},DEFAULTS]]]:= Module[{xscale, yscale,w0,w,h,cl,z,bytes,k,li,pi},*)
(*{xscale, yscale} = {N[OptionValue[ScalingFactor][[1]]], N[OptionValue[ScalingFactor][[2]]]};*)
(*w=IntegerPart[OptionValue[Width]];*)
(*h=IntegerPart[OptionValue[Height]];*)
(*cl=If[OptionValue[Clamp],1, 0];*)
(*li =IntegerPart[l];*)
(*pi  =IntegerPart[p];*)
(**)
(*k=N[OptionValue[WaveVector]];*)
(*w0=N[OptionValue[BeamWaist]];*)
(*z=N[OptionValue[Z]];*)
(**)
(*bytes=Check[LaguerreGuassianPhase[*)
(*w, h, xscale, yscale, li, pi, k,w0,z,cl*)
(*],Abort[]];*)
(**)
(*If[OptionValue[Raw], bytes, Image[bytes]]*)
(*];*)
(**)
(*TwoLGPhase[l0_, p0_,l1_,p1_, OptionsPattern[Join[{Raw-> False},DEFAULTS]]]:= Module[{xscale, yscale,w0,w,h,cl,z,bytes,k,l1i,l0i,p1i,p0i},*)
(*{xscale, yscale} = {N[OptionValue[ScalingFactor][[1]]], N[OptionValue[ScalingFactor][[2]]]};*)
(*w=IntegerPart[OptionValue[Width]];*)
(*h=IntegerPart[OptionValue[Height]];*)
(*cl=If[OptionValue[Clamp],1, 0];*)
(*l0i =IntegerPart[l0];*)
(*p0i =IntegerPart[p0];*)
(*l1i =IntegerPart[l1];*)
(*p1i =IntegerPart[p1];*)
(**)
(*k=N[OptionValue[WaveVector]];*)
(*w0=N[OptionValue[BeamWaist]];*)
(*z=N[OptionValue[Z]];*)
(**)
(*bytes=Check[TwoLaguerreGuassianPhase[*)
(*w, h, xscale, yscale, l0i, p0i,l1i,p1i, k,w0,z,cl*)
(*],Abort[]];*)
(**)
(*If[OptionValue[Raw], bytes, Image[bytes]]*)
(*];*)
(**)
(*TwoLGMag[l0_, p0_,l1_,p1_, OptionsPattern[Join[{Raw-> False},DEFAULTS]]]:= Module[{xscale, yscale,w0,w,h,cl,z,bytes,k,l1i,l0i,p1i,p0i},*)
(*{xscale, yscale} = {N[OptionValue[ScalingFactor][[1]]], N[OptionValue[ScalingFactor][[2]]]};*)
(*w=IntegerPart[OptionValue[Width]];*)
(*h=IntegerPart[OptionValue[Height]];*)
(*cl=If[OptionValue[Clamp],1, 0];*)
(*l0i =IntegerPart[l0];*)
(*p0i =IntegerPart[p0];*)
(*l1i =IntegerPart[l1];*)
(*p1i =IntegerPart[p1];*)
(**)
(*k=N[OptionValue[WaveVector]];*)
(*w0=N[OptionValue[BeamWaist]];*)
(*z=N[OptionValue[Z]];*)
(**)
(*bytes=Check[TwoLaguerreGuassianMag[*)
(*w, h, xscale, yscale,l0i, p0i,l1i,p1i, k,w0,z,cl*)
(*],Abort[]];*)
(**)
(*If[OptionValue[Raw], bytes, Image[bytes]]*)
(*];*)
(**)
